sudo: required

services:
	-docker

language: bash

before_script:
	-"docker build -t steffzug/autobuilds ."
	-"docker container run --detach --publish 8080:80 steffzug/autobuilds"
	-docker ps

script:
	-while ! curl --retry 10 --retry-delay 5 -v http://10.8.0.123:8080/dev/null; do sleep 1; done

